version: "3"
services:

  tenant:
    image: designre/tenant:v1.0
    container_name: tenant
    ports:
      - 8080:8080
    depends_on:
      - mysql2
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tenantnet

  mysql2:
    container_name: mysql2
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: tenant
      MYSQL_USER: tenant
      MYSQL_PASSWORD: Bv87Kk3z.IP2020
    restart: always
    volumes:
      - mysql-volume2:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tenantnet

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/nginx.conf2:/etc/nginx/nginx.conf
    depends_on:
      - tenant
    networks:
      - tenantnet

volumes:
  mysql-volume2:
networks:
  tenantnet:
    driver: overlay
    attachable: true