server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Bv87Kk3z.IP2020
        url: jdbc:mysql://mysql2:3306/tenant
        username: tenant
    jpa:
        hibernate:
            ddl-auto: update
multitenancy:
    http:
        header-name: X-TENANT-ID
jasypt:
    encryptor:
        password: apvR5t3wABsvJKJufku5Yb5v9n7accqk7JRT4nQEgEkJN2btF7
        algorithm: PBEWithMD5AndDES